data:
  repo: https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/
  filename: dpc-covid19-ita-regioni-
  dateformat: YYYYmmdd
  extension: csv
  first_date: 20200224
logging:
  filename: log.log
  # INFO, DEBUG, WARNING
  level: INFO
